In [12]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from scipy.stats import pearsonr

In [6]:
# Carga del Datasets
df = pd.read_csv("../datasets/movies_ML.csv")

In [7]:
df.head(40)

,presupuesto (mill),genero,idioma_original,popular,estreno,ganancia (mill),duracion,titulo,prom_voto,anio,retorno
0,30.00,"['animation', 'comedy', 'family']",en,21.946943,1995-10-30,373.554033,81.0,toy story,Excelente,1995,12.45
1,65.00,"['adventure', 'fantasy', 'family']",en,17.015539,1995-12-15,262.797249,104.0,jumanji,Bueno,1995,4.04
2,0.00,"['romance', 'comedy']",en,11.712900,1995-12-22,0.000000,101.0,grumpier old men,Bueno,1995,0.00
3,16.00,"['comedy', 'drama', 'romance']",en,3.859495,1995-12-22,81.452156,127.0,waiting to exhale,Bueno,1995,5.09
4,0.00,['comedy'],en,8.387519,1995-02-10,76.578911,106.0,father of the bride part ii,Promedio,1995,0.00
5,60.00,"['action', 'crime', 'drama', 'thriller']",en,17.924927,1995-12-15,187.436818,170.0,heat,Excelente,1995,3.12
6,58.00,"['comedy', 'romance']",en,6.677277,1995-12-15,0.000000,127.0,sabrina,Bueno,1995,0.00
7,0.00,"['action', 'adventure', 'drama', 'family']",en,2.561161,1995-12-22,0.000000,97.0,tom and huck,Promedio,1995,0.00
8,35.00,"['action', 'adventure', 'thriller']",en,5.231580,1995-12-22,64.350171,106.0,sudden death,Promedio,1995,1.84
9,58.00,"['adventure', 'action', 'thriller']",en,14.686036,1995-11-16,352.194034,130.0,goldeneye,Bueno,1995,6.07
10,62.00,"['comedy', 'drama', 'romance']",en,6.318445,1995-11-17,107.879496,106.0,the american president,Bueno,1995,1.74
11,0.00,"['comedy', 'horror']",en,5.430331,1995-12-22,0.000000,88.0,dracula: dead and loving it,Promedio,1995,0.00
12,0.00,"['family', 'animation', 'adventure']",en,12.140733,1995-12-22,11.348324,78.0,balto,Excelente,1995,0.00
13,44.00,"['history', 'drama']",en,5.092000,1995-12-22,13.681765,192.0,nixon,Excelente,1995,0.31
14,98.00,"['action', 'adventure']",en,7.284477,1995-12-22,10.017322,119.0,cutthroat island,Promedio,1995,0.10
15,52.00,"['drama', 'crime']",en,10.137389,1995-11-22,116.112375,178.0,casino,Excelente,1995,2.23
16,16.50,"['drama', 'romance']",en,10.673167,1995-12-13,135.000000,136.0,sense and sensibility,Excelente,1995,8.18
17,4.00,"['crime', 'comedy']",en,9.026586,1995-12-09,4.300000,98.0,four rooms,Bueno,1995,1.07
18,30.00,"['crime', 'comedy', 'adventure']",en,8.205448,1995-11-10,212.385533,90.0,ace ventura: when nature calls,Bueno,1995,7.08
19,60.00,"['action', 'comedy', 'crime']",en,7.337906,1995-11-21,35.431113,103.0,money train,Promedio,1995,0.59
20,30.25,"['comedy', 'thriller', 'crime']",en,12.669608,1995-10-20,115.101622,105.0,get shorty,Bueno,1995,3.81
21,0.00,"['drama', 'thriller']",en,10.701801,1995-10-27,0.000000,124.0,copycat,Bueno,1995,0.00
22,50.00,"['action', 'adventure', 'crime', 'thriller']",en,11.065939,1995-10-06,30.303072,132.0,assassins,Bueno,1995,0.61
23,0.00,"['drama', 'fantasy', 'science fiction', 'thril...",en,12.133094,1995-10-27,0.000000,111.0,powder,Bueno,1995,0.00
24,3.60,"['drama', 'romance']",en,10.332025,1995-10-27,49.800000,112.0,leaving las vegas,Excelente,1995,13.83
25,0.00,['drama'],en,1.845899,1995-12-15,0.000000,123.0,othello,Excelente,1995,0.00
26,12.00,"['comedy', 'drama', 'family']",en,8.681325,1995-10-20,27.400000,100.0,now and then,Bueno,1995,2.28
27,0.00,"['drama', 'romance']",en,2.228434,1995-09-27,0.000000,104.0,persuasion,Excelente,1995,0.00
28,18.00,"['fantasy', 'science fiction', 'adventure']",fr,9.822423,1995-05-16,1.738611,108.0,the city of lost children,Excelente,1995,0.10
29,0.00,"['drama', 'crime']",zh,1.100915,1995-04-30,0.000000,108.0,shanghai triad,Bueno,1995,0.00
30,0.00,"['drama', 'crime']",en,9.481338,1995-08-11,180.000000,99.0,dangerous minds,Bueno,1995,0.00
31,29.50,"['science fiction', 'thriller', 'mystery']",en,12.297305,1995-12-29,168.840000,129.0,twelve monkeys,Excelente,1995,5.72
32,0.00,"['romance', 'adventure']",fr,0.745542,1996-09-18,0.000000,50.0,wings of courage,Bueno,1996,0.00
33,30.00,"['fantasy', 'drama', 'comedy', 'family']",en,14.404764,1995-07-18,254.134910,89.0,babe,Bueno,1995,8.47
34,0.00,"['history', 'drama', 'romance']",en,1.493361,1995-11-08,0.000000,121.0,carrington,Bueno,1995,0.00
35,11.00,['drama'],en,6.891317,1995-12-29,39.363635,122.0,dead man walking,Excelente,1995,3.58
36,0.00,"['adventure', 'history', 'drama', 'family']",en,0.114469,1995-10-20,0.000000,51.0,across the sea of time,Promedio,1995,0.00
37,0.00,"['comedy', 'family', 'romance']",en,7.777735,1995-11-17,0.000000,101.0,it takes two,Bueno,1995,0.00
38,12.00,"['comedy', 'drama', 'romance']",en,9.882383,1995-07-19,0.000000,97.0,clueless,Bueno,1995,0.00
39,0.00,['drama'],en,0.894647,1995-12-15,0.676525,106.0,"cry, the beloved country",Bueno,1995,0.00

In [17]:
def recommend_movies(data, movie_title):
    # Filtrar la película de referencia
    reference_movie = data[data['titulo'] == movie_title]
    
    # Calcular la correlación de Pearson entre la película de referencia y el resto de películas
    correlation_scores = data[['prom_voto']].apply(lambda x: pearsonr(reference_movie['prom_voto'], x)[0], axis=0)
    
    # Crear una serie con los títulos de las películas y sus puntuaciones de correlación
    correlation_scores_series = pd.Series(correlation_scores, index=data['titulo'])
    
    # Ordenar las películas según la puntuación de correlación en orden descendente
    sorted_movies = correlation_scores_series.sort_values(ascending=False)
    
    # Obtener las 5 películas más similares (excluyendo la película de referencia)
    recommended_movies = sorted_movies[1:6]
    
    return recommended_movies.index.tolist()

In [25]:

def recommend_movies(data, movie_title):
    # Filtrar la película de referencia
    reference_movie = data[data['titulo'] == movie_title]
    
    # Obtener las puntuaciones de votos de la película de referencia
    reference_votes = reference_movie['prom_voto']
    
    # Calcular la correlación de Pearson entre la película de referencia y el resto de películas
    correlation_scores = data[['prom_voto']].apply(lambda x: pearsonr(reference_votes, x)[0], axis=0)
    
    # Crear una serie con los títulos de las películas y sus puntuaciones de correlación
    correlation_scores_series = pd.Series(correlation_scores, index=data['titulo'])
    
    # Ordenar las películas según la puntuación de correlación en orden descendente
    sorted_movies = correlation_scores_series.sort_values(ascending=False)
    
    # Obtener las 5 películas más similares (excluyendo la película de referencia)
    recommended_movies = sorted_movies[1:6]
    })
    
    return recommended_movies.index.tolist()


# Ejemplo de uso
df = pd.DataFrame({
    'presupuesto (mill)': [30.00, 65.00, 0.00, 16.00, 0.00],
    'genero': [['animation', 'comedy', 'family'], ['adventure', 'fantasy', 'family'], ['romance', 'comedy'], ['comedy', 'drama', 'romance'], ['comedy']],
    'idioma_original': ['en', 'en', 'en', 'en', 'en'],
    'popular': [21.946943, 17.015539, 11.712900, 3.859495, 8.387519],
    'estreno': ['1995-10-30', '1995-12-15', '1995-12-22', '1995-12-22', '1995-02-10'],
    'ganancia (mill)': [373.554033, 262.797249, 0.000000, 81.452156, 76.578911],
    'duracion': [81.0, 104.0, 101.0, 127.0, 106.0],
    'titulo': ['toy story', 'jumanji', 'grumpier old men', 'waiting to exhale', 'father of the bride part ii'],
    'prom_voto': ['Excelente', 'Bueno', 'Bueno', 'Bueno', 'Promedio'],
    'anio': [1995, 1995, 1995, 1995, 1995],
    'retorno': [12.45, 4.04, 0.00, 5.09, 0.00]
}

SyntaxError: unmatched '}' (2762380961.py, line 19)

In [ ]:
movie_title = 'toy story'
recommended_movies = recommend_movies(df, movie_title)
print(recommended_movies)

In [ ]:

    
  
    # Crear una serie con los títulos de las películas y sus puntuaciones de correlación
    correlation_scores_series = pd.Series(correlation_scores, index=data['titulo'])
    
    # Ordenar las películas según la puntuación de correlación en orden descendente
    sorted_movies = correlation_scores_series.sort_values(ascending=False)
    
    # Obtener las 5 películas más similares (excluyendo la película de referencia)
    recommended_movies = sorted_movies[1:6]
    
    return recommended_movies.index.tolist()

# Ejemplo de uso
data = pd.DataFrame({
    'presupuesto (mill)': [30.00, 65.00, 0.00, 16.00, 0.00],
    'genero': [['animation', 'comedy', 'family'], ['adventure', 'fantasy', 'family'], ['romance', 'comedy'], ['comedy', 'drama', 'romance'], ['comedy']],
    'idioma_original': ['en', 'en', 'en', 'en', 'en'],
    'popular': [21.946943, 17.015539, 11.712900, 3.859495, 8.387519],
    'estreno': ['1995-10-30', '1995-12-15', '1995-12-22', '1995-12-22', '1995-02-10'],
    'ganancia (mill)': [373.554033, 262.797249, 0.000000, 81.452156, 76.578911],
    'duracion': [81.0, 104.0, 101.0, 127.0, 106.0],
    'titulo': ['toy story', 'jumanji', 'grumpier old men', 'waiting to exhale', 'father of the bride part ii'],
    'prom_voto': ['Excelente', 'Bueno', 'Bueno', 'Bueno', 'Promedio'],
    'anio': [1995, 1995, 1995, 1995, 1995],
    'retorno': [12.45, 4.04, 0.00, 5.09, 0.00]
})

movie_title = 'toy story'
recommended_movies = recommend_movies(data, movie_title)
print(recommended_movies)

In [8]:
def recommend_movies(data, movie_title):
    # Filtrar la película de referencia
    reference_movie = df[df['titulo'] == movie_title]
    
    # Calcular la similitud de puntuación entre la película de referencia y el resto de películas
    similarity_scores = cosine_similarity(reference_movie[['prom_voto']], df[['prom_voto']])
    
    # Crear una serie con los títulos de las películas y sus puntuaciones de similitud
    similarity_scores_series = pd.Series(similarity_scores[0], index=data['titulo'])
    
    # Ordenar las películas según la puntuación de similitud en orden descendente
    sorted_movies = similarity_scores_series.sort_values(ascending=False)
    
    # Obtener las 5 películas más similares (excluyendo la película de referencia)
    recommended_movies = sorted_movies[1:6]
    
    return recommended_movies.index.tolist()

In [ ]:
# Ejemplo de uso
data = pd.DataFrame({
    'presupuesto (mill)': [30.00, 65.00, 0.00, 16.00, 0.00],
    'genero': [['animation', 'comedy', 'family'], ['adventure', 'fantasy', 'family'], ['romance', 'comedy'], ['comedy', 'drama', 'romance'], ['comedy']],
    'idioma_original': ['en', 'en', 'en', 'en', 'en'],
    'popular': [21.946943, 17.015539, 11.712900, 3.859495, 8.387519],
    'estreno': ['1995-10-30', '1995-12-15', '1995-12-22', '1995-12-22', '1995-02-10'],
    'ganancia (mill)': [373.554033, 262.797249, 0.000000, 81.452156, 76.578911],
    'duracion': [81.0, 104.0, 101.0, 127.0, 106.0],
    'titulo': ['toy story', 'jumanji', 'grumpier old men', 'waiting to exhale', 'father of the bride part ii'],
    'prom_voto': ['Excelente', 'Bueno', 'Bueno', 'Bueno', 'Promedio'],
    'anio': [1995, 1995, 1995, 1995, 1995],
    'retorno': [12.45, 4.04, 0.00, 5.09, 0.00]
})

movie_title = 'toy story'
recommended_movies = recommend_movies(data, movie_title)
print(recommended_movies)

In [9]:
movie_title = 'toy story'
recommended_movies = recommend_movies(data, movie_title)
print(recommended_movies)

NameError: name 'data' is not defined

In [ ]:
# Cambiar los caracteres solo en las columnas categoricas
def convert_special_characters(item):
    if isinstance(item, str):
        return unidecode(item)
    elif isinstance(item, list):
        return [convert_special_characters(x) for x in item]
    elif isinstance(item, dict):
        return {k: convert_special_characters(v) for k, v in item.items()}
    else:
        return item

# Obtener las columnas categóricas
columnas_categoricas = df.select_dtypes(include=['object']).columns

# Aplicar convert_special_characters solo a las columnas categóricas
df[columnas_categoricas] = df[columnas_categoricas].applymap(convert_special_characters)

In [ ]:
# Covirtiendo las mayusculas a minúsculas
def convert_to_lowercase(item):
    if isinstance(item, str):
        return item.lower()
    elif isinstance(item, list):
        return [convert_to_lowercase(x) for x in item]
    elif isinstance(item, dict):
        return {k: convert_to_lowercase(v) for k, v in item.items()}
    else:
        return item

# Obtener las columnas categóricas
columnas_categoricas = df.select_dtypes(include=['object']).columns

# Aplicar convert_to_lowercase solo a las columnas categóricas
df[columnas_categoricas] = df[columnas_categoricas].applymap(convert_to_lowercase)

In [ ]:
# Canbiando el tipo de variable
df['anio'] = df['anio'].astype(str)
df.dtypes

In [ ]:
pues la funcion final me quedo asi: def test(selected_title):
    """ 
    Esta función toma el título de una película como entrada y devuelve una lista de las 5 películas más recomendadas basadas en similitud y puntaje utilizando el algoritmo KNN.
    
    """ 
    df = pd.read_csv('movies_dataset_reduced.csv') 
    k = 6
    generos_df = pd.read_csv('genres_binary.csv', index_col=0).astype('float32')

    selected_genres = df.loc[df['title'] == selected_title]['genres'].values[0]
    df['genre_similarity'] = df['genres'].apply(lambda x: len(set(selected_genres) & set(x)) / len(set(selected_genres) | set(x)))
    df['same_series'] = df['title'].apply(lambda x: 1 if 'Batman' in x else 0)
    features_df = pd.concat([generos_df, df['vote_average'], df['genre_similarity'], df['same_series']], axis=1)
    knn = NearestNeighbors(n_neighbors=k+1, algorithm='auto')
    knn.fit(features_df)
    indices = knn.kneighbors(features_df.loc[df['title'] == selected_title])[1].flatten()
    recommended_movies = list(df.iloc[indices]['title'])
    recommended_movies = sorted(recommended_movies, key=lambda x: (df.loc[df['title'] == x]['same_series'].values[0], df.loc[df['title'] == x]['vote_average'].values[0], df.loc[df['title'] == x]['genre_similarity'].values[0]), reverse=True)
    recommended_movies = [movie for movie in recommended_movies if movie != selected_title]
    return recommended_movies[0:5]

In [ ]:
con este codigo conviertes a binario la columna de generos : df = pd.read_csv('movies_dataset_reduced.csv')
df['genres'] = df['genres'].apply(ast.literal_eval)
genreList = ['History', 'Animation', 'Mystery', 'Comedy', 'Documentary', 'War', 'Action', 'Romance', 'Family', 'Adventure', 'Thriller', 'Fantasy', 'TV Movie', 'Crime', 'Music', 'Horror', 'Drama', 'Foreign', 'Science Fiction', 'Western']
generos_df = pd.DataFrame(columns=genreList, index=df.index)
for i, row in df.iterrows():
    genres = row['genres']
    for genre in genres:
        if genre in genreList:
            generos_df.loc[i, genre] = 1
generos_df.fillna(0, inplace=True)
generos_df.to_csv('genres_binary.csv')

In [ ]:
def recomendacion(titulo):
    pelicula_seleccionada = df[df['title'] == titulo]
    if pelicula_seleccionada.empty:
        return {'lista recomendada': 'No se encontró la película'}
    
    # Calcular la correlación de puntuaciones con otras películas
    correlaciones = df.corrwith(pelicula_seleccionada['puntuacion'])
    
    # Filtrar películas con una correlación alta (más similares)
    peliculas_similares = correlaciones.sort_values(ascending=False).head(6)[1:]
    
    # Obtener los nombres de las películas similares
    nombres_similares = df.loc[peliculas_similares.index, 'title'].tolist()
    
    return {'lista recomendada': nombres_similares}

In [ ]:
recomendacion('Jumanjy')

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.cluster import hierarchy

# Supongamos que tienes un DataFrame llamado 'df' con tus datos

# Calcula la matriz de correlación
corr_matrix = df.corr()

# Calcula las distancias entre las columnas
distances = hierarchy.distance.pdist(corr_matrix)

# Calcula el enlace jerárquico
linkage = hierarchy.linkage(distances, method='complete')

# Dibuja el dendrograma
plt.figure(figsize=(10, 6))
dendrogram = hierarchy.dendrogram(linkage, labels=corr_matrix.columns, leaf_rotation=90)
plt.xlabel('Columnas')
plt.ylabel('Distancia')
plt.title('Dendrograma de correlación de columnas')
plt.show()